//
// Created by OLEKSANDR SOKOLOV on 12/26/20.
//

#ifndef CPPUNIVERSITYPROJECT_DEFAULTMOBS_H
#define CPPUNIVERSITYPROJECT_DEFAULTMOBS_H


class DefaultMobs {

};


#endif //CPPUNIVERSITYPROJECT_DEFAULTMOBS_H
