//
// Created by OLEKSANDR SOKOLOV on 12/26/20.
//

#ifndef CPPUNIVERSITYPROJECT_DUNGEONBOSS_H
#define CPPUNIVERSITYPROJECT_DUNGEONBOSS_H


class DungeonBoss {

};


#endif //CPPUNIVERSITYPROJECT_DUNGEONBOSS_H
