//
// Created by OLEKSANDR SOKOLOV on 12/26/20.
//

#ifndef CPPUNIVERSITYPROJECT_TYPESOFDAMAGE_H
#define CPPUNIVERSITYPROJECT_TYPESOFDAMAGE_H


class TypesOfDamage {

};


#endif //CPPUNIVERSITYPROJECT_TYPESOFDAMAGE_H
